### ISSUE TITLE
Does alloc operation fail?

### ISSUE THREAD

**Issue by decentralisedkev** [interstellar/zkvm#22]
https://github.com/interstellar/zkvm/blob/main/spec/ZkVM.md#alloc

To clarify the alloc operation:

 Is a variable `var1` popped from the stack? 

Also are these the failing conditions:
 -  cs produces a R1CSError
 - `var1` is not a variable

**Comment by oleganza** [comment]
`alloc` never fails because it does not take any inputs. Prover commits to its assignment via vector commitment `A_I` within the r1cs proof (see bulletproofs documentation).

**Comment by decentralisedkev** [comment]
> Prover commits to its assignment via vector commitment A_I

Okay, my mistake.
